trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'YourAzureSubscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalKey) --tenant $(tenantId)
        az account set --subscription $(subscriptionId)
        az group create --name $(resourceGroupName) --location $(resourceGroupLocation)
        az deployment group create --resource-group $(resourceGroupName) --template-file ./IaC/main.bicep --parameters ./IaC/parameters.json
    displayName: 'Deploy Bicep template'
